version: '3.9'

services:
    postgres:
        image: postgres:16.1-alpine
        ports:
            - "5433:5432"
        volumes:
            - pgsql_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    pgsql_volume:
